Description: "Parent Stack for Codepipeline Deploy Template Git Sync Configuration"
Parameters:
  SuggestedStackName:
    Type: "String"
    Description: "If creating through the AWS Console, this is the suggested stack name.  Copy and paste this value for the stack name."
    Default: "codepipeline-deploy-git-sync"
Resources:
  GitSyncSetupWaitCondition:
    Type: "AWS::CloudFormation::WaitConditionHandle"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "General Configuration"
      Parameters:
      - SuggestedStackName
    ParameterLabels:
      # General Configuration
      SuggestedStackName:
        default: "Suggested Stack Name:"